name: Build and publish Sphinx docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: Build Sphinx HTML
        run: |
          sphinx-build -E -b html docs/source docs/build

      - name: Upload artifact for GitHub Pages
        # use v2 if available — se Github segnala ancora problema, prova a rimuovere/aggiornare questa action
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1